name = "hetzner-firewall-cfworker"
main = "src/index.ts"
workers_dev = true
compatibility_date = "2023-07-01"
#logpush = true

[vars]
PORTS = "replace_with_your_ports" # e.g. "80,443"
FIREWALL_ID = "replace_with_your_firewall_id"

[triggers]
crons = ["0 0 * * *"]
